repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: coolpipe
  description: A cool pipeline
  author: me
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
